services:
  solr:
    image: solr:9.6.1
    volumes:
      - $PWD/solr/conf:/opt/solr/conf
    ports:
      - 8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5555
      POSTGRES_DB: geoblacklight_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5555:5432